### ISSUE TITLE
Submit to wp.org

### ISSUE THREAD

**Issue by kraftbj** [pmgllc/genesis-minimum-images-extended#11]
Do you want to request submission into the WP.org repo? 
http://wordpress.org/extend/plugins/add/

We can start that now, beta while we await review, so we can launch it on the wp.org once we're happy that we are bug-free.

**Comment by pmgllc** [comment]
Sure, I'll do that tonight and I know a few people on Twitter were interested. I'll put it on my production sites to test over the weekend.

How do we ditch the -master branch filename and the .git files for repo? Manually or some new setup in GitHub?

**Comment by kraftbj** [comment]
I know there are some automated ways, but what I do personally is have a
separate folder (e.g. wp-org-genesis-enews-extended) that I have sync'd via
SVN to the plugins repo server. When I copy/paste things over, I remove the
.git folder/files.

## 

Brandon J. Kraft
_Coffea Web Services_

brandonkraft.com · coffeaweb.com

@kraft http://twitter.com/kraft · @coffeawebhttp://twitter.com/coffeaweb

Tel: 512-476-3761 · 877-563-2467

SMS: 512-696-0411

**Comment by kraftbj** [comment]
To clarify - submit the ZIP for the review, and when approved, they'll make an area on the plugins repo for us and we're asked to do the work of actually putting it up via SVN.

**Comment by pmgllc** [comment]
I don't have a clue about SVN yet so I used a Mac zip-creator that strips out the Mac files and uploaded it to my hosting for their URL to test it.

## I edited the description upon submission but didn't update the readme.txt yet. Here's what I submitted:

Allows for a specialized image for the "header" image above a post or page's content while allowing a different feature image to be used in the grid loop, Facebook, Pinterest, etc.

## This is intended for the child theme Minimum 2.0 for the Genesis framework. We plan on expanding the child themes and functionality as it evolves and StudioPress releases more themes that use featured images to enhance the design but where developers and users may want extended options.

**Comment by kraftbj** [comment]
I know little about SVN. Same idea as Git, just a different system. I
installed TortoiseSVN (seemingly the GUI of choice for Windows and SVN) and
just know enough to pull and commit changes to my plugin and pull down the
latest WP trunk. (I did, after a few tries, get a patch to work that I
submitted against core... it's really the most advanced, useful patch ever
in the history of patches -- http://core.trac.wordpress.org/ticket/22987 I
know, I know. Forget photomatt. I'll be the keynote at WCSF this year).

I digress.

Like I mentioned, I have a separate folder in my code folder for the wp-org
version of the plugin. Apparently standard in a SVN repo is three folders:
branches, tags and trunk. When I "freeze" a new release (e.g. tell myself
it's a new release), I copy the contents to a new folder in tags (e.g.
tags/0.1.5). Typically, I copy it to trunk also (in my case, if there's
something I want to beta test, I copy it to trunk without putting it in a
tag... I'll get to that in a second).

The WP repo reads the stable tag line of the readme.txt header in the trunk
folder to determine which "tags" folder to use as _the_ version to offer
folks (or to upgrade to). In theory, you could have tags/0.1, tags/0.2,
tags/0.3 and if the readme.txt in trunk has a stable tag of 0.1, no one,
without hunting around, would ever know about 0.2 and 0.3.

All versions (e.g. each "tags" folder) is available in the Developers tab (
ex: http://wordpress.org/extend/plugins/genesis-enews-extended/developers/).
The trunk version is the "Development Version". For instance, with the
just released 0.1.6 for enews, I didn't want to bother with supporting it
even though the code had been ready for a couple of weeks. When people
asked, I directed them to the Development Version on the wp.org repo page
(the plugins.php file was marked 0.1.6-beta1). When 0.1.6 was released and
the readme.txt in trunk was advanced from 0.1.5 to 0.1.6, everyone on 0.1.5
and 0.1.6-beta1 were offered the upgraded version.

Back to SVN itself, similar to Git, once you copy the files to the folders
within the repo, you'll need to "add" them. Once added, then you commit
them. As the plugin author, it'll ask you to login and it'll push it to the
repo. After ~5 min, it'll be available and ready to go.

I hope that makes sense. Don't really know much beyond that for SVN!

## 

Brandon J. Kraft
_Coffea Web Services_

 brandonkraft.com · coffeaweb.com

@kraft http://twitter.com/kraft · @coffeawebhttp://twitter.com/coffeaweb

Tel: 512-476-3761 · 877-563-2467

SMS: 512-696-0411

**Comment by pmgllc** [comment]
They're making me change Nick's affiliate link to a link to StudioPress. I'm going to edit it, re-zip, and tell them I replaced the file they reviewed. That was their only issue.

**Comment by kraftbj** [comment]
I didn't catch that. Good call on their part.

## 

Brandon J. Kraft
_Coffea Web Services_

brandonkraft.com · coffeaweb.com

@kraft http://twitter.com/kraft · @coffeawebhttp://twitter.com/coffeaweb

Tel: 512-476-3761 · 877-563-2467

SMS: 512-696-0411
