### ISSUE TITLE
Activation server 500 error

### ISSUE THREAD

**Issue by pmgllc** [pmgllc/genesis-minimum-images-extended#4]
I put the plugin in another site of mine running Minimum 2.0 and it slapped me again. I'm going to look at the server logs and see what I can find out and really do some learning.

**Comment by pmgllc** [comment]
Error log:

[Mon Jan 07 02:15:03 2013] [error] [client 108.33.105.50] PHP Warning:  require_once(/nas/wp/www/cluster-1474/cffatboy/wp-content/plugins/genesis-minimum-images-extended/classes/init.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory in /nas/wp/www/cluster-1474/cffatboy/wp-content/plugins/genesis-minimum-images-extended/plugin.php on line 92, referer: http://www.cffatboy.com/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s=

[Mon Jan 07 02:15:03 2013] [error] [client 108.33.105.50] PHP Fatal error:  require_once() [<a href='function.require'>function.require</a>]: Failed opening required '/nas/wp/www/cluster-1474/cffatboy/wp-content/plugins/genesis-minimum-images-extended/classes/init.php' (include_path='.:/usr/share/php:/usr/share/pear') in /nas/wp/www/cluster-1474/cffatboy/wp-content/plugins/genesis-minimum-images-extended/plugin.php on line 92, referer: http://www.cffatboy.com/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s=

**Comment by kraftbj** [comment]
Interesting. If I click to download the ZIP from GitHub, the classes folder is empty (probably because I abstracted out to a submodule).

If I actually clone the repo via git, it's there. Don't know if that might be related to your current issue.

**Comment by kraftbj** [comment]
Scratch that. It works in my repo, but if I clone again, it's gone. Let me revert those changes until I can advise better on submodules.

**Comment by pmgllc** [comment]
Okay - I am clicking the Zip button, no cloning. Is that the wrong way? My classes folder was blank, yes.

**Comment by kraftbj** [comment]
I have to read up on submodules. My understanding was that it should have pulled down the CMB repo, but I missed something.

Try again -- either way -- I went back to the old way of just having a copy of a classes folder. Let's get it working and once everyone is happy, then I can screw around with stuff I don't really know yet :-)

**Comment by pmgllc** [comment]
;-) I'll re-d/l and try again.

**Comment by kraftbj** [comment]
With cloning, apparently that is how it is to be (blank classes folder). Two commands are needed to pull down the submodule. I would expect the zip to do that for you, going to request that feature for github.

Assuming that fixed your issue, closing issue.
