### ISSUE TITLE
Stuck with 300px banner

### ISSUE THREAD

**Issue by pmgllc** [pmgllc/genesis-minimum-images-extended#7]
I created a staging area and got the following to work: http://jpetersen.staging.wpengine.com/business-tips/thoughts-on-competition-among-wordpress-developers/

It is insisting on using the 300px thumbnail of the banner file and I can't see how to avoid that. I removed the banner's custom image size - it needs to be the full 100% width, auto height (or the actual height).

![Screen Shot 2013-01-09 at 12 36 48 AM](https://f.cloud.github.com/assets/1641678/52689/56e26da8-5a22-11e2-9ece-6147d6535d16.png)
![Screen Shot 2013-01-09 at 12 37 09 AM](https://f.cloud.github.com/assets/1641678/52690/56e1ebb2-5a22-11e2-9f3b-85831b34c08b.png)

Very proud of myself for figuring out most of the issues I caused by changing course to concentrate on just the banner. Anyone know how to use the full image instead of a thumb?

**Comment by pmgllc** [comment]
It looks like it calling in a 300px banner is a result of not assigning the ID to it to call the header or gmie-banner image size. Found this on Bill Erickson's post on CMB, but no further description:

-File upload. Use the built-in media uploader to allow the user to upload any file they want. You can also store the attachment ID in case you want to retrieve other image sizes.

Any ideas on how to retrieve image size in output.php line 24 or line 26?

**Comment by kraftbj** [comment]
I know I've done it, but don't remember offhand how. I can dig around
tonight after girls go to sleep.

## 

Brandon Kraft
Coffea Web Services
http://coffeaweb.com // http://brandonkraft.com
@kraft

**Comment by pmgllc** [comment]
Thanks. I can surely wait for that. I gave it more than a college try.

**Comment by kraftbj** [comment]
Pulled in changes made by Bill. Marking issue closed.

**Comment by pmgllc** [comment]
It's still an issue, but I'm going to try to find the cause now that we have a filter. It's not displaying any image and it is still pulling in the 300x59px image, as indicated here. I can't just correct the filename and update the post, either.

I'll take a look after we straighten out these foster issues.
![Screen Shot 2013-01-09 at 5 24 30 PM](https://f.cloud.github.com/assets/1641678/54941/76afdede-5aab-11e2-8786-3b08547342bb.png)

**Comment by pmgllc** [comment]
I've decided that it's possible the field entered is just because something elsewhere is commanding it. That particular size is the 'medium' media size in my install. I don't see any call for 'medium' in the CMB files nor our admin file. I was able to save the filename in the field as the full 1600px image size, but when I refreshed, I still got the same results as below.

I haven't made any changes to GitHub because I was making so many uneducated guesses on my sandbox, it was going to be several dozen changes for nothing.

I did some code testing to what Bill did and I changed this at the end of output.php in my sandbox and I got the echo displayed, meaning it's seeing the entry as empty.
![Screen Shot 2013-01-09 at 8 57 16 PM](https://f.cloud.github.com/assets/1641678/55423/23c73456-5ac9-11e2-8a2d-2a2495694d24.png)

Starting at line 23:
elseif ( is_singular( array( 'post', 'page' ) ) ) {
    $custom_image_id = genesis_get_custom_field( '_gmie_image_id' );
    if( empty( $custom_image_id ) ) {
        echo 'hello';
        }

---

So perhaps that's the wrong get command. So I tried others:

elseif ( is_singular( array( 'post', 'page' ) ) ) {
    $banner_image_id = wp_get_attachment_image_src( get_post_meta( $post->ID, '_gmie_id', true ), 'full' );
    if( empty( $banner_image_id ) ) {
        echo 'hello';

##         }

elseif ( is_singular( array( 'post', 'page' ) ) ) {
    $banner_image_id = wp_get_attachment_image_src( get_post_meta( $post->ID, '_gmie_id', true ), 'gmie-banner' );
    if( empty( $banner_image_id ) ) {
        echo 'hello';

##         }

elseif ( is_singular( array( 'post', 'page' ) ) ) {
    $banner_image = wp_get_attachment_image_src( get_post_meta( $post->ID, '_gmie_id', true ), 'gmie-banner' );
    if( empty( $banner_image ) ) {
        echo 'hello';
        }

**Comment by kraftbj** [comment]
Let me reset my sandbox and start over with this.

**Comment by pmgllc** [comment]
I can do chat in an hour or so. Wife took my laptop to Facebook again.

**Comment by kraftbj** [comment]
Where do you stand on this? I have it working ( http://sp.brandonkraft.net/2012/11/13/hello-world/ ), ignoring the image alignment... as far as picture size goes.

**Comment by pmgllc** [comment]
I still have a failed empty field test showing "hello" in my copy. Let me
grab the newest and see if anything you did fixed that.

I don't see any images at all on the post you linked.

**Comment by kraftbj** [comment]
Check it now at http://sp.brandonkraft.net/2012/11/13/hello-world/ . I was
playing with possible options (e.g. no banner selected, but feature image
set) and apparently left it w/o a banner image.

**Comment by pmgllc** [comment]
Headed to a meeting. Probably around 2:00 I can.

**Comment by pmgllc** [comment]
It is confirmed working now. See below - banners differ from post image, which is the featured image
http://jpetersen.staging.wpengine.com/business-tips/thoughts-on-competition-among-wordpress-developers/
http://jpetersen.staging.wpengine.com/business-tips/introducing-the-success-concept-of-win-win-win/

The featured images are shown here
http://jpetersen.staging.wpengine.com/blog/
and here
http://jpetersen.staging.wpengine.com/

That's the functionality I was looking for. Great, let's do a beta release.
